//
//  CreateOrderInteractor.swift
//  CleanStore
//
//  Created by Managam Silalahi on 12/6/16.
//  Copyright (c) 2016 Managam Silalahi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol CreateOrderInteractorInput
{
    var shippingMethods: [String] { get }
    func formatExpirationDate(request: CreateOrder_FormatExpirationDate_Request)
}

protocol CreateOrderInteractorOutput
{
    func presentExpirationDate(response: CreateOrder_FormatExpirationDate_Response)
}

class CreateOrderInteractor: CreateOrderInteractorInput
{
    var output: CreateOrderInteractorOutput!
    var worker: CreateOrderWorker!
    var shippingMethods = ["Standard Shipping",
                           "Two-day Shipping",
                           "One-day Shipping"]
    
    // MARK: - Expiration Date
    
    func formatExpirationDate(request: CreateOrder_FormatExpirationDate_Request)
    {
        let response = CreateOrder_FormatExpirationDate_Response(date: request.date)
        output.presentExpirationDate(response: response)
    }
}
