//
//  CreateOrderModels.swift
//  CleanStore
//
//  Created by Managam Silalahi on 12/6/16.
//  Copyright (c) 2016 Managam Silalahi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct CreateOrder_FormatExpirationDate_Request
{
    var date: Date
}

struct CreateOrder_FormatExpirationDate_Response
{
    var date: Date
}

struct CreateOrder_FormatExpirationDate_ViewModel
{
    var date: String
}
